CREATE TABLE `t_credential` (
  `CRD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CRD_LOGIN` varchar(45) NOT NULL,
  `CRD_PASS` varchar(45) NOT NULL,
  `CRD_ROLE` varchar(45) DEFAULT NULL,
  `CRD_FIRST_NAME` varchar(45) DEFAULT NULL,
  `CRD_LAST_NAME` varchar(45) DEFAULT NULL,
  `CRD_AUDIT_CD` date DEFAULT NULL,
  `CRD_AUDIT_MD` date DEFAULT NULL,
  `CRD_AUDIT_RD` date DEFAULT NULL,
  PRIMARY KEY (`CRD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
